# Generated by Django 5.1.3 on 2024-11-30 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='QuizSession',
        ),
    ]
